# Generated by Django 5.2.6 on 2025-09-18 06:26

import catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_product_created_at_alter_product_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productmedia',
            options={'ordering': ['-is_primary', 'id']},
        ),
        migrations.AddField(
            model_name='productmedia',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='productmedia',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=catalog.models.product_media_upload_to),
        ),
    ]
